### ISSUE TITLE
Filter not working as expected

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/nodes-dashboard#62]
If you type an id in the search input I works ok
if you type {id} {id} it return nothing.

For example searching for: `16Uiu2HAmD5X8hJ3ScRoAUPwDLRc6U6UkP4qYdppHdS4TmQwjKpPC 16Uiu2HAky9NEzeDVnXAm6EJnQuKXqo2nevGqTw2i434rR3ybgJNt` returns nothing, both are valid ids

**Comment by jamiehewitt15** [comment]
So you want a match for either {id} or {id}? The table uses the MUI X data grid and their search functionality. I'm not sure if this will be possible while using that library... So this might be more work that it initially seems.
