### ISSUE TITLE
Reseting filters/search not working

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/nodes-dashboard#63]
Sometimes after resetting the filter and/or search the table is still empty

**Comment by hoysal08** [comment]
https://github.com/user-attachments/assets/f3c10ea1-1d82-4a6d-a47a-0c81f40b2d98

Hey, after seeing your report i tried to replicate it. Looks like we get into this invalid state where the rows don't match search input/filters.

Possible fix
- add the api call on the remove Focus from Input Field
